import { createHash } from "node:crypto";

// Idempotency for the flight request without touching the shared database
// schema. The form mints one random submission key per mounted form and sends
// it with every attempt (including Next.js's own automatic retry of a failed
// Server Action POST). Lead.id is a plain string primary key whose cuid()
// default is generated by the Prisma client, not the database — so the
// server can supply the id itself, derived deterministically from that key.
// The same logical submission then always targets the same primary key, and
// the database's own uniqueness guarantee turns a second attempt into a
// no-op: no extra column, no CRM migration, and no heuristic on name, route
// or date (two genuinely separate requests carry different keys).
//
// Shape: "c" + 24 hex characters = 25 characters starting with "c", the same
// shape as the cuid() ids the CRM generates, so anything in the CRM that
// treats a lead id as an opaque token (links, queries, logs) is unaffected.
// Hashing (rather than using the key directly) keeps the id unguessable from
// anything but the key itself, and namespaces it away from every other id.
export function deriveLeadId(submissionId: string): string {
  return "c" + createHash("sha256").update(`business-flights-travel:flight-request:${submissionId}`).digest("hex").slice(0, 24);
}
